name: Run EF Core Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Instalar EF Core CLI
        run: dotnet tool install --global dotnet-ef

      # O passo de forcar o IPv4 foi removido.

      - name: Rodar migrations
        run: dotnet ef database update --project api/TccSolidario.Api
        env:
          ConnectionStrings__DefaultConnection: "Host=aws-1-us-east-1.pooler.supabase.com;Database=postgres;Username=postgres.wqgrxpnjelgixasitbzo;Password=${{ secrets.DB_PASSWORD }};SSL Mode=Require;Trust Server Certificate=true"
          Jwt__Key: ${{ secrets.JWT_KEY }}